import colors from './colors';

const boxSizing = 'border-box';

const Selects = {
  SelectComponent: {
    selectedValue: {
      background: 'rgba(0,0,0,0)',
      border: `1px solid ${colors.colorsTheme.grey}`,
      boxSizing: boxSizing,
      borderRadius: 12.5,
      display: 'flex',
      color: colors.colorsTheme.text,
      marginLeft: 10,
      paddingLeft: 6,
      paddingRight: 6,
      marginBottom: 5,
      marginTop: 5,
      fontSize: 12,
      lineHeight: '20px',
    },
    closeTagIcon: {
      width: 14,
      cursor: 'pointer',
      height: 14,
      marginTop: 3,
      marginLeft: 3,
    },
    closeTagIconWrapper: {
      width: 20,
      height: 20,
      marginRight: -6,
    },
    selectedValues: {
      width: '100%',
      height: 38,
      lineHeight: '38px',
      padding: '0 10px',
      color: colors.colorsTheme.grey,
      whiteSpace: 'nowrap',
      textOverflow: 'ellipsis',
      wordBreak: 'break-all',
      overflow: 'hidden',
      paddingRight: 0,
    },
    inputField: {
      background: 'rgba(0,0,0,0)',
      border: 0,
      fontSize: 'inherit',
      opacity: 1,
      outline: 0,
      padding: '6px 16px',
      color: '#fff',
      width: '100%',
      boxSizing: boxSizing,
    },
    root: {},
    label: {
      color: colors.colorsTheme.grey,
      fontSize: 12,
      marginBottom: 6,
    },
    select: {
      width: '100%',
      minHeight: 34,
      background: colors.colorsTheme.input,
      borderRadius: 8,
      display: 'flex',
      cursor: 'pointer',
    },
    splitLine: {
      width: 1,
      background: '#fff',
      marginTop: 5,
      marginBottom: 5,
      alignSelf: 'stretch',
      boxSizing: boxSizing,
      '-webkit-align-self': 'stretch',
    },
    controlElements: {
      display: 'flex',
      fontSize: 'large',
      alignItems: 'center',
      color: colors.colorsTheme.grey,
      cursor: 'pointer',
      height: 'inherit',
      flexWrap: 'wrap-reverse',
      padding: '0 5px',
    },
    popover: {
      width: 350,
      background: colors.colorsTheme.background,
      color: colors.colorsTheme.grey,
      padding: 15,
    },
    inputRoot: {
      marginBottom: 15,
      width: '100%',
    },
    listRoot: { padding: 0 },
    selectedValueLabel: {
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
    },
    closePopupButton: {
      padding: '6px 25px',
      margin: 'auto',
      marginRight: 0,
      '&:hover': {
        color: '#fff',
      },
    },
    horizontalSeparator: {
      height: 1,
      width: '100%',
      background: colors.colorsTheme.input,
      marginTop: 12,
      marginBottom: 12,
    },
    rotate: { '& svg': { transform: 'rotate(180deg)' } },
    menuIcon: {
      '& svg': {
        transition: 'all 300ms ease-in-out',
        width: 10,
        height: '100%',
        margin: '0 16px',
      },
      '& path': { fill: colors.colorsTheme.grey },
    },
    hidden: { visibility: 'hidden' },
    disableSelect: { cursor: 'default' },
  },
  multiSelecComponent: {
    selectedValue: {
      background: 'rgba(0,0,0,0)',
      border: `1px solid ${colors.colorsTheme.grey}`,
      boxSizing: boxSizing,
      borderRadius: 12.5,
      display: 'flex',
      color: colors.colorsTheme.text,
      marginLeft: 10,
      paddingLeft: 6,
      paddingRight: 6,
      marginBottom: 5,
      marginTop: 5,
      fontSize: 12,
      lineHeight: '20px',
      height: 'fit-content',
      minHeight: 22,
      maxWidth: 150,
    },
    label: {
      color: colors.colorsTheme.grey,
      fontSize: 12,
      marginBottom: 6,
    },
    selectedValues: {
      display: 'flex',
      flexWrap: 'wrap',
      width: '100%',
    },
    inputField: {
      background: 'rgba(0,0,0,0)',
      border: 0,
      fontSize: 'inherit',
      opacity: 1,
      outline: 0,
      padding: '6px 16px',
      color: '#fff',
      width: '100%',
      boxSizing: boxSizing,
    },
    root: {
      width: '100%',
      minHeight: 38,
      background: colors.colorsTheme.input,
      borderRadius: 8,
      display: 'flex',
    },
    splitLine: {
      width: 1,
      background: '#fff',
      marginTop: 5,
      marginBottom: 5,
      alignSelf: 'stretch',
      boxSizing: boxSizing,
      '-webkit-align-self': 'stretch',
    },
    controlElements: {
      display: 'flex',
      fontSize: 'large',
      alignItems: 'center',
      color: colors.colorsTheme.grey,
      cursor: 'pointer',
      height: 'inherit',
      flexWrap: 'wrap-reverse',
      padding: '0 5px',
    },
    popover: {
      width: 350,
      background: colors.colorsTheme.background,
      color: colors.colorsTheme.grey,
      padding: 15,
    },
    inputRoot: { marginBottom: 15 },
    listRoot: { padding: 0 },
    selectedValueLabel: {
      display: 'flex',
      alignItems: 'center',
      textOverflow: 'ellipsis',
      whiteSpace: 'nowrap',
      wordBreak: 'break-all',
      overflow: 'hidden',
    },
    closePopupButton: {
      padding: '6px 25px',
      margin: 'auto',
      marginRight: 0,
      '&:hover': {
        color: '#fff',
      },
    },
    horizontalSeparator: {
      height: 1,
      width: '100%',
      background: colors.colorsTheme.input,
      marginTop: 12,
      marginBottom: 12,
    },
  },
};

export default Selects;
