const model = {
  code: 200,
  msg: null,
  data: {
    model: {
      value: 'periods-test',
      label: 'periods-test',
      block: 'Тестовые модели',
      tribe: 1,
      description: null,
      resources: [
        {
          nodeId: null,
          value: 'node1',
          label: 'Node 12',
          supres: null,
          category: 'server',
          description: null,
          lifeTime: 1,
          color: null,
          position: { fx: null, fy: null, x: null, y: null, z: null },
          metrics: ['wpds'],
          coreMetric: null,
          uses: [],
          nodeParameters: [],
          parameters: [],
          fixedTariff: false,
          budcycles: [
            {
              id: 14,
              label: '2020',
              required: [],
              available: [],
              purchased: [],
              depreciated: [],
              proportions: [],
              tariffs: [],
              consumptions: [],
              fixed: [
                { costId: 'amort', price: 0.0 },
                { costId: 'capex', price: 0.0 },
                { costId: 'opex', price: 0.0 },
              ],
              variable: [],
              totals: { full: 0.0, direct: 0.0, left: 0.0 },
              fixedTariff: false,
            },
            {
              id: 57,
              label: '2021',
              required: [],
              available: [],
              purchased: [],
              depreciated: [],
              proportions: [],
              tariffs: [],
              consumptions: [],
              fixed: [
                { costId: 'amort', price: 0.0 },
                { costId: 'capex', price: 0.0 },
                { costId: 'opex', price: 0.0 },
              ],
              variable: [],
              totals: { full: 0.0, direct: 0.0, left: 0.0 },
              fixedTariff: false,
            },
          ],
          link: null,
          groupName: null,
          group: false,
        },
        {
          nodeId: null,
          value: 'val-246434634',
          label: 'test',
          supres: null,
          category: 'storage',
          description: null,
          lifeTime: 1,
          color: null,
          position: { fx: null, fy: null, x: 18.0, y: -16.0, z: 49.0 },
          metrics: [],
          coreMetric: null,
          uses: ['node1'],
          nodeParameters: [],
          parameters: [],
          fixedTariff: false,
          budcycles: [
            {
              id: 14,
              label: '2020',
              required: [],
              available: [],
              purchased: [],
              depreciated: [],
              proportions: [],
              tariffs: [],
              consumptions: [],
              fixed: [
                { costId: 'amort', price: 110.0 },
                { costId: 'capex', price: 110.0 },
                { costId: 'opex', price: 110.0 },
              ],
              variable: [],
              totals: { full: 330.0, direct: 330.0, left: 330.0 },
              fixedTariff: false,
            },
            {
              id: 57,
              label: '2021',
              required: [],
              available: [],
              purchased: [],
              depreciated: [],
              proportions: [],
              tariffs: [],
              consumptions: [],
              fixed: [
                { costId: 'amort', price: 110.0 },
                { costId: 'capex', price: 110.0 },
                { costId: 'opex', price: 110.0 },
              ],
              variable: [],
              totals: { full: 330.0, direct: 330.0, left: 330.0 },
              fixedTariff: false,
            },
          ],
          link: null,
          groupName: null,
          group: false,
        },
      ],
      metricDictionary: [
        {
          id: 51,
          value: 'test_volch',
          label: 'test',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['software'],
          isGlobal: true,
        },
        {
          id: 50,
          value: 'volchanskiy_test',
          label: 'test_v',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['server'],
          isGlobal: true,
        },
        {
          id: 47,
          value: 'mmm',
          label: 'Sample',
          description: null,
          author: null,
          authorFullName: null,
          modelName: 'ahd_new4',
          cats: [],
          isGlobal: true,
        },
        {
          id: 45,
          value: 'nkm',
          label: 'Количество КМ',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['business_unit'],
          isGlobal: true,
        },
        {
          id: 44,
          value: 'Gb4',
          label: 'Трафик 4',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['Network4'],
          isGlobal: true,
        },
        {
          id: 43,
          value: 'Gb3',
          label: 'Трафик 3',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['Network3'],
          isGlobal: true,
        },
        {
          id: 42,
          value: 'Gb2',
          label: 'Трафик 3',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['Network2'],
          isGlobal: true,
        },
        {
          id: 41,
          value: 'Gb1',
          label: 'Трафик 1',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['NetWork1'],
          isGlobal: true,
        },
        {
          id: 40,
          value: 'wpds',
          label: 'Рабочее место DS',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'server', 'software'],
          isGlobal: true,
        },
        {
          id: 39,
          value: 'user',
          label: 'Пользователи',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'business_unit', 'fp'],
          isGlobal: true,
        },
        {
          id: 38,
          value: 'unit',
          label: 'Unit',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['inf', 'software'],
          isGlobal: true,
        },
        {
          id: 37,
          value: 'tpy',
          label: 'Транзакций/год',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['fp'],
          isGlobal: true,
        },
        {
          id: 36,
          value: 'tps',
          label: 'Транзакций/сек',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'business_unit', 'fp', 'platform', 'software'],
          isGlobal: true,
        },
        {
          id: 35,
          value: 'tpd',
          label: 'Транзакций/день',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['fp'],
          isGlobal: true,
        },
        {
          id: 34,
          value: 'testenv',
          label: 'Тестовая среда',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'element'],
          isGlobal: true,
        },
        {
          id: 33,
          value: 'Tb',
          label: 'Тбайт',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['inf', 'software'],
          isGlobal: true,
        },
        {
          id: 32,
          value: 'supplier',
          label: 'Поставщик',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app'],
          isGlobal: true,
        },
        {
          id: 31,
          value: 'subsc',
          label: 'Подписки',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['fp'],
          isGlobal: true,
        },
        {
          id: 30,
          value: 'ssps',
          label: 'Простой поиск/сек',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['platform'],
          isGlobal: true,
        },
        {
          id: 29,
          value: 'sht',
          label: 'Штука',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'server'],
          isGlobal: true,
        },
        {
          id: 28,
          value: 'rsvps',
          label: 'Получений/сек',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'platform'],
          isGlobal: true,
        },
        {
          id: 27,
          value: 'req_sec',
          label: 'Запросов/сек',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'business_unit', 'element'],
          isGlobal: true,
        },
        {
          id: 26,
          value: 'pstpd',
          label: 'Проводка/день',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app'],
          isGlobal: true,
        },
        {
          id: 25,
          value: 'pst',
          label: 'Проводка',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'business_unit'],
          isGlobal: true,
        },
        {
          id: 24,
          value: 'platezh_sec',
          label: 'Платёж/сек',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'element'],
          isGlobal: true,
        },
        {
          id: 23,
          value: 'pl',
          label: 'Платеж',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['business_unit'],
          isGlobal: true,
        },
        {
          id: 22,
          value: 'paydoc_day',
          label: 'Платежный документ/день',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app'],
          isGlobal: true,
        },
        {
          id: 21,
          value: 'ops',
          label: 'Операций/секунду',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'business_unit', 'element', 'platform'],
          isGlobal: true,
        },
        {
          id: 20,
          value: 'oph',
          label: 'Операций/час',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'element'],
          isGlobal: true,
        },
        {
          id: 19,
          value: 'op',
          label: 'Операции (шт)',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'business_unit'],
          isGlobal: true,
        },
        {
          id: 18,
          value: 'nvsp',
          label: 'Офисы ВСП',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['business_unit'],
          isGlobal: true,
        },
        {
          id: 17,
          value: 'nserv',
          label: 'Количество серверов',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'business_unit', 'element', 'storage'],
          isGlobal: true,
        },
        {
          id: 16,
          value: 'message',
          label: 'Сообщений/сек',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'inf', 'platform', 'software', 'storage', 'support'],
          isGlobal: true,
        },
        {
          id: 15,
          value: 'merch',
          label: 'Мерчант',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['business_unit', 'element'],
          isGlobal: true,
        },
        {
          id: 14,
          value: 'iops',
          label: 'IOPS',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['storage', 'vendor'],
          isGlobal: true,
        },
        {
          id: 13,
          value: 'invoice',
          label: 'Начисления',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'storage'],
          isGlobal: true,
        },
        {
          id: 12,
          value: 'inst',
          label: 'Инстанс',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'business_unit', 'element', 'storage'],
          isGlobal: true,
        },
        {
          id: 11,
          value: 'Gb',
          label: 'Гбайт',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: [
            'app',
            'fp',
            'inf',
            'platform',
            'server',
            'software',
            'storage',
            'vendor',
          ],
          isGlobal: true,
        },
        {
          id: 10,
          value: 'fte',
          label: 'ПШЕ',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['change', 'fp', 'software', 'support', 'vendor'],
          isGlobal: true,
        },
        {
          id: 9,
          value: 'fsps',
          label: 'Полный поиск/сек',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'inf', 'platform', 'software', 'storage', 'support'],
          isGlobal: true,
        },
        {
          id: 8,
          value: 'document',
          label: 'Документ',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'business_unit', 'element', 'storage'],
          isGlobal: true,
        },
        {
          id: 7,
          value: 'customers',
          label: 'Клиенты',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'business_unit', 'element', 'storage'],
          isGlobal: true,
        },
        {
          id: 6,
          value: 'credit',
          label: 'Количество кредитных дороворов',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'fp', 'platform', 'storage'],
          isGlobal: true,
        },
        {
          id: 5,
          value: 'CR',
          label: 'change request',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['change', 'fp'],
          isGlobal: true,
        },
        {
          id: 4,
          value: 'core',
          label: 'Ядро',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'inf', 'server', 'software'],
          isGlobal: true,
        },
        {
          id: 3,
          value: 'contract',
          label: 'Договор',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['software', 'vendor'],
          isGlobal: true,
        },
        {
          id: 2,
          value: 'client',
          label: 'Клиент',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'storage'],
          isGlobal: true,
        },
        {
          id: 1,
          value: 'block',
          label: 'Блоки КТС',
          description: null,
          author: null,
          authorFullName: null,
          modelName: null,
          cats: ['app', 'element', 'fp', 'server'],
          isGlobal: true,
        },
      ],
      periodDictionary: [
        { id: 14, label: '2020', type: 'Y', year: 2020 },
        { id: 57, label: '2021', type: 'Y', year: 2021 },
      ],
      resCategories: [
        {
          id: 2,
          value: 'storage',
          label: 'Хранение данных',
          description:
            'Комплексное программно-аппаратное решение по организации надёжного хранения информационных ресурсов (Hi-end, Mid-range, др)',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 4,
          value: 'inf',
          label: 'Инфраструктурное оборудование',
          description:
            'Программно-аппаратные комплексы, которые созданы для решения интеграционных задач',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 7,
          value: 'platform',
          label: 'Платформа',
          description:
            'Логическое объединение технологий и сервисов, предназначенное для создания бизнес-приложений (определение Платформы в соответствие со стандартом “Platform-Ready”',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 8,
          value: 'element',
          label: 'Внутренние элементы модели',
          description:
            'объект расчета тарифа, используемый для детализации финансовой модели и не относящийся к другим категориям справочника',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 9,
          value: 'support',
          label: 'ДИТ_сопровождение',
          description: 'Ресурсы ДИТ, которые занимаются сопровождением ПО',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 10,
          value: 'change',
          label: 'ДИТ_разработка',
          description:
            'Ресурсы ДИТ, которые занимаются разработкой, тестированием ПО',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 11,
          value: 'vendor',
          label: 'Вендор',
          description:
            'Ресурсы СБТ и внешних подрядчиков, которые совместно с ДИТ занимаются разработкой, тестированием ПО',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 12,
          value: 'business_unit',
          label: 'Объект расчета финансового результата',
          description:
            'Подразделение/конечный продукт/канал/сегмент, на котором собираются расходы по АС',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 14,
          value: 'NetWork1',
          label: 'Сеть1',
          description: 'Ресурсы потребления сетевого трафика АС',
          author: null,
          modelName: null,
          color: '#D4E157',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 15,
          value: 'Network2',
          label: 'Сеть2',
          description: 'ресурсы потребления сетевого трафика АС 2',
          author: null,
          modelName: null,
          color: '#8D6E63',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 17,
          value: 'Network4',
          label: 'Сеть4',
          description: 'ресерсы потребления сетевого трафика АС 4',
          author: null,
          modelName: null,
          color: '#42A5F5',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 16,
          value: 'Network3',
          label: 'Сеть3',
          description: 'ресурсы потребления сетевого трафика АС 3',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff'],
          subCategories: [],
        },
        {
          id: 5,
          value: 'app',
          label: 'Автоматизированная система (АС)',
          description:
            'Самостоятельный объект управления в ИТ-процессах, представляющий собой набор разработанных или заимствованных компонентов ПО, реализующих логически связанный набор функциональности для выполнения необходимых бизнес-задач, а также для поддержки других АС',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['payment'],
          subCategories: [],
        },
        {
          id: 1,
          value: 'server',
          label: 'Серверная инфраструктура',
          description:
            'Оборудование для выполнения на нём сервисного программного обеспечения (x86, Sparc, др)',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff', 'payment'],
          subCategories: [],
        },
        {
          id: 3,
          value: 'software',
          label: 'Серверное ПО',
          description: 'Серверное программное обеспечение и база данных',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff', 'payment'],
          subCategories: [],
        },
        {
          id: 6,
          value: 'fp',
          label: 'Функциональная подсистема (ФП)',
          description:
            'Дополнительный к АС объект управления в ИТ-процессах, представляющий собой совокупность компонентов ПО, реализующую логически связанное подмножество функциональности АС',
          author: null,
          modelName: null,
          color: '#EF5350',
          isGlobal: true,
          calcTypes: ['tariff', 'payment'],
          subCategories: [],
        },
      ],
      costDictionary: [
        { value: 'amort', label: 'AMORT', type: 'amort' },
        { value: 'capex', label: 'CAPEX', type: 'capex' },
        { value: 'opex', label: 'OPEX', type: 'opex' },
      ],
      parameters: [
        {
          id: 1,
          value: 'Тестовый код параметра',
          label: 'Тестовое наименование параметра',
          volume: 42.0,
          description: 'Тестовое описание параметра',
          authorId: 'admin',
          authorFullName: 'Админов Админ Админович',
          modelName: 'Тестовое имя модели',
          isGlobal: true,
        },
        {
          id: 2,
          value: 'test_id',
          label: 'test',
          volume: 1.0,
          description: 'тест',
          isGlobal: true,
        },
        {
          id: 6,
          value: 'n',
          label: 'n',
          volume: 13.0,
          description: 'n',
          isGlobal: true,
        },
      ],
      stage: { id: 1, label: 'Создание/доработка модели' },
      author: 'zhulev.f.al@sberbank.ru',
      tariffModel: false,
    },
    permissions: [
      { code: 'CREATE', description: 'Создать' },
      { code: 'READ', description: 'Просмотр' },
      { code: 'UPDATE', description: 'Редактировать' },
      { code: 'DELETE', description: 'Удалить' },
      { code: 'ALLOW', description: 'Разрешить' },
    ],
    lockedInfo: {
      username: 'zhulev.f.al@sberbank.ru',
      fullName: null,
      avatar: '',
    },
    locked: false,
  },
};

export { model };